<#
.SYNOPSIS
  Deploys PABEL's managed-settings.json / managed-mcp.json (generated by
  `pabel-connector generate-managed-settings`) to their real enforced
  locations on THIS machine.

.DESCRIPTION
  Two separate files, two separate rules - see connector/docs/managed-settings.md
  before running this:

    - managed-settings.json (hooks: allowManagedHooksOnly/allowManagedPermissionRulesOnly)
      can go either to the registry (GPO/Intune-style) or to a file under
      C:\Program Files\ClaudeCode\ - pick with -Mode.
    - managed-mcp.json (MCP server exclusive-control) is ALWAYS file-based -
      it cannot be delivered through the registry/server-managed-settings
      channel at all, so this script always copies it to
      C:\Program Files\ClaudeCode\managed-mcp.json regardless of -Mode.

  This is an admin-only, machine-wide, deliberately manual step - it is not
  run by pabel-connector itself and not run automatically by anything in
  this repo. Run it as Administrator, on the machine actually being managed,
  after reviewing what it's about to write (-WhatIf supported).

.PARAMETER ManagedSettingsPath
  Path to the generated managed-settings.json (default: .\managed-settings.json)

.PARAMETER ManagedMcpPath
  Path to the generated managed-mcp.json (default: .\managed-mcp.json)

.PARAMETER Mode
  "File" (default) or "Registry" - where managed-settings.json's hook/permission
  policy is deployed. managed-mcp.json is unaffected by this switch (see above).

.EXAMPLE
  pabel-connector generate-managed-settings --out-dir . --python-path "C:\PabelPython\python.exe"
  .\Deploy-ManagedSettings.ps1 -Mode File -WhatIf
  .\Deploy-ManagedSettings.ps1 -Mode File
#>

[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
param(
    [string]$ManagedSettingsPath = ".\managed-settings.json",
    [string]$ManagedMcpPath = ".\managed-mcp.json",
    [ValidateSet("File", "Registry")]
    [string]$Mode = "File"
)

$ErrorActionPreference = "Stop"

$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
    ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    throw "Deploy-ManagedSettings.ps1 must be run as Administrator - it writes to " +
          "C:\Program Files\ClaudeCode\ and/or HKLM:\SOFTWARE\Policies\ClaudeCode, " +
          "neither of which a standard user account can write to (by design - " +
          "that's exactly what makes this enforcement not employee-removable)."
}

if (-not (Test-Path $ManagedSettingsPath)) {
    throw "managed-settings.json not found at '$ManagedSettingsPath' - generate it first: " +
          "pabel-connector generate-managed-settings --out-dir . --python-path <machine-wide-python>"
}
if (-not (Test-Path $ManagedMcpPath)) {
    throw "managed-mcp.json not found at '$ManagedMcpPath' - generate it first: " +
          "pabel-connector generate-managed-settings --out-dir . --python-path <machine-wide-python>"
}

# Fail loudly on malformed JSON here rather than deploying it - a malformed
# managed-settings.json is the one failure mode managed-settings.md calls out
# as most dangerous (Claude Code silently ignores the whole managed layer and
# falls back to user/project settings, with no visible error).
$settingsJson = Get-Content $ManagedSettingsPath -Raw
$null = $settingsJson | ConvertFrom-Json
$mcpJson = Get-Content $ManagedMcpPath -Raw
$null = $mcpJson | ConvertFrom-Json

$claudeCodeDir = "C:\Program Files\ClaudeCode"

if ($Mode -eq "Registry") {
    $regPath = "HKLM:\SOFTWARE\Policies\ClaudeCode"
    if ($PSCmdlet.ShouldProcess("$regPath\Settings", "Set managed-settings.json content")) {
        New-Item -Path $regPath -Force | Out-Null
        Set-ItemProperty -Path $regPath -Name "Settings" -Value $settingsJson -Type String
        Write-Host "Wrote $regPath\Settings (registry, string value)."
    }
} else {
    if ($PSCmdlet.ShouldProcess("$claudeCodeDir\managed-settings.json", "Write file")) {
        New-Item -Path $claudeCodeDir -ItemType Directory -Force | Out-Null
        Copy-Item $ManagedSettingsPath "$claudeCodeDir\managed-settings.json" -Force
        Write-Host "Wrote $claudeCodeDir\managed-settings.json"
    }
}

# managed-mcp.json: always file-based, regardless of -Mode - see doc header above.
if ($PSCmdlet.ShouldProcess("$claudeCodeDir\managed-mcp.json", "Write file")) {
    New-Item -Path $claudeCodeDir -ItemType Directory -Force | Out-Null
    Copy-Item $ManagedMcpPath "$claudeCodeDir\managed-mcp.json" -Force
    Write-Host "Wrote $claudeCodeDir\managed-mcp.json"
}

Write-Host ""
Write-Host "Deployed. Verify from a real Claude Code session on this machine:"
Write-Host "  /status              -> 'Setting sources' must show the managed layer active"
Write-Host "                          (e.g. (HKLM) or (file)), not just user/project."
Write-Host "  claude mcp list      -> must show only pabel/pabel-connector."
Write-Host "  claude mcp add ...   -> must fail with an explicit enterprise-policy error."
Write-Host "If any of these don't hold, do not consider this deployment complete - see"
Write-Host "connector/docs/managed-settings.md's 'one failure mode that matters most'."
