// PABEL bridge plugin for opencode. Generated by `pabel-connector install
// opencode` - re-run install to regenerate rather than editing by hand.
//
// Contains NO policy of its own: it forwards one tool call to the hook and
// applies whatever adapters/opencode.py renders back, so every decision
// stays in core/decide.py, shared with every other agent. It exists only
// because opencode loads plugins in-process instead of invoking a command
// from a config file.
//
// Protocol: see adapters/opencode.py's docstring.

import { spawn } from "node:child_process";

const HOOK_ARGV = __PABEL_HOOK_ARGV__;
const TIMEOUT_MS = __PABEL_TIMEOUT_MS__;

// Fails CLOSED on anything unexpected: a missing interpreter, a crash or a
// timeout must block, never silently let a direct .abe read through.
function askPabel(tool, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(HOOK_ARGV[0], HOOK_ARGV.slice(1), {
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    let settled = false;

    // The hook may legitimately block for minutes: decide() runs an
    // interactive browser+MFA login when there's no valid session yet. Set
    // from HOOK_TIMEOUT_SECONDS so it can't drift below what that needs.
    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      child.kill();
      reject(new Error(`pabel-connector hook timed out after ${TIMEOUT_MS}ms`));
    }, TIMEOUT_MS);

    child.stdout.on("data", (chunk) => (stdout += chunk));
    child.stderr.on("data", (chunk) => (stderr += chunk));

    child.on("error", (err) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      reject(err);
    });

    child.on("close", (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (code !== 0) {
        reject(new Error(`pabel-connector hook exited ${code}: ${stderr.trim()}`));
        return;
      }
      try {
        resolve(JSON.parse(stdout || "{}"));
      } catch (e) {
        reject(new Error(`pabel-connector hook returned unparseable output: ${stdout}`));
      }
    });

    child.stdin.write(JSON.stringify({ tool, args }));
    child.stdin.end();
  });
}

export const PabelPlugin = async () => ({
  "tool.execute.before": async (input, output) => {
    let decision;
    try {
      decision = await askPabel(input.tool, output.args);
    } catch (err) {
      // See askPabel's own comment: deny, never fall through.
      throw new Error(
        `PABEL could not evaluate this tool call, so it was blocked rather ` +
          `than allowed through: ${err.message}`
      );
    }

    if (decision.permission === "deny") {
      // Throwing is the only way to block, and this message is the only thing
      // that travels with it - the relayed result is already folded in.
      throw new Error(decision.message || "Blocked by PABEL.");
    }

    if (decision.updated_args) {
      // Injects this installation's agent credential into a direct call to
      // the deployed server's tools, without the model ever seeing it.
      Object.keys(output.args).forEach((k) => delete output.args[k]);
      Object.assign(output.args, decision.updated_args);
    }
  },
});
