"""Client-side, confidentiality-only audit log of PABEL-relevant decide()
outcomes - a deliberately different guarantee from relay.report_denial()'s
server-side audit trail, not a replacement for it.

Read this before assuming it protects against a malicious agent: it does
not, and cannot. Whatever process can legitimately append a new entry here
(this installation's own hook subprocess) necessarily has the local code
execution needed to also delete this file, stop writing to it, or - since
it holds the same public key this module uses to encrypt - forge a new
entry that decrypts just as cleanly as a real one. Encryption here defends
against a *third party* who later gets hold of this file (a stolen laptop,
a backup, a misconfigured file share), never against the agent it records.
The one guarantee that DOES hold against the audited agent itself is
report_denial()'s: never persisting anything locally in the first place.
See docs/known-gaps.md's "Client-side audit log" section.

Hybrid RSA-OAEP + AES-256-GCM, one company-wide keypair (not one per
machine - see server/agents_admin.py's generate-audit-keypair): RSA alone
cannot encrypt an arbitrary-size payload (roughly key_size/8 minus OAEP's
own overhead), so each entry generates a fresh, one-time AES-256 key,
encrypts the entry with it (AES-256-GCM, a fresh random 96-bit nonce every
time), then wraps that one-time key with the company's RSA public key.
Only whoever holds the matching RSA private key - deliberately never the
running PABEL server, never this endpoint, only IT/whoever ran
generate-audit-keypair - can recover it (agents_admin.py's
decrypt-audit-log).
"""

import base64
import json
import os
import time
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

DATA_DIR = Path(os.environ.get("PABEL_PLUGIN_DATA_DIR") or Path.home() / ".pabel")
PUBLIC_KEY_FILE = DATA_DIR / "audit_public_key.pem"
LOG_FILE = DATA_DIR / "audit.log.enc"

_OAEP_PADDING = padding.OAEP(
    mgf=padding.MGF1(algorithm=hashes.SHA256()), algorithm=hashes.SHA256(), label=None)


def load_public_key():
    """None if no --audit-public-key was given at install time - absence is
    a normal, silent "this feature is off" state, not an error (see
    append_entry(), the only caller that matters at runtime)."""
    if not PUBLIC_KEY_FILE.exists():
        return None
    return serialization.load_pem_public_key(PUBLIC_KEY_FILE.read_bytes())


def install_public_key(source_path) -> Path:
    """Copies an admin-provided PEM public key (generated by
    agents_admin.py's generate-audit-keypair) to this installation's own
    fixed location - called once, at `pabel-connector install --audit-
    public-key ...` time, never regenerated here (this module never creates
    a keypair - only IT does, since only IT is ever meant to hold the
    matching private key)."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    data = Path(source_path).read_bytes()
    serialization.load_pem_public_key(data)  # fail fast on a bad/wrong-type key, before writing
    PUBLIC_KEY_FILE.write_bytes(data)
    return PUBLIC_KEY_FILE


def encrypt_entry(public_key, entry: dict) -> str:
    """One base64 line: a 2-byte big-endian length prefix, the RSA-OAEP-
    wrapped AES key, a 12-byte AES-GCM nonce, then the ciphertext - length-
    prefixed so decrypt_entry (agents_admin.py) can split a wrapped key of
    whatever size this keypair produces back out unambiguously."""
    plaintext = json.dumps(entry).encode("utf-8")
    aes_key = AESGCM.generate_key(bit_length=256)
    nonce = os.urandom(12)
    ciphertext = AESGCM(aes_key).encrypt(nonce, plaintext, None)
    wrapped_key = public_key.encrypt(aes_key, _OAEP_PADDING)
    return base64.b64encode(len(wrapped_key).to_bytes(2, "big") + wrapped_key
                            + nonce + ciphertext).decode("ascii")


def append_entry(agent_id, tool_name, decision_kind, target, reason):
    """Best-effort, same spirit as relay.report_denial(): a missing public
    key (this feature was never turned on for this installation), a
    malformed key file, or any other encryption failure must never affect
    what decide() itself returns - only whether this specific, purely
    complementary record gets written. Never raises."""
    try:
        public_key = load_public_key()
        if public_key is None:
            return
        entry = {
            "ts": time.time(), "agent_id": agent_id, "tool_name": tool_name,
            "decision_kind": decision_kind, "target": target, "reason": reason,
        }
        line = encrypt_entry(public_key, entry)
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        with open(LOG_FILE, "a", encoding="ascii") as f:
            f.write(line + "\n")
    except Exception:
        pass
